# Generated by Django 3.2.5 on 2021-07-28 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0002_delete_mymodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='CrudOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('email', models.EmailField(blank=True, max_length=60, null=True)),
            ],
        ),
    ]
